spring.application.name=hadoop-backend
# Server konfiguratsiyasi
server.port=8080
server.address=0.0.0.0

# Application nomi

# File upload sozlamalari
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

# Logging
logging.level.root=INFO
logging.level.com.bigdata=DEBUG
logging.level.org.apache.hadoop=WARN